name: "default"
description: "default"
inputs:
  submodules:
    description: "Whether to checkout submodules"
    default: false
  python-version:
    description: "Python version"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: ${{ inputs.submodules }}
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version || env.PYTHON_VERSION || '3.10' }}
