name: "default"
description: "default"
inputs:
  title:
    description: "Milestone title"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7.0.1
      with:
        script: |
          const title = '${{ inputs.title }}'
          const milestones = await github.rest.issues.listMilestones({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const milestoneExists = milestones.data.some(m => m.title === title);
          if (!milestoneExists) {
            await github.rest.issues.createMilestone({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
            });
            console.log(`Milestone '${title}' created successfully!`);
          } else {
            console.log(`Milestone '${title}' already exists.`);
          }
