name: "default"
description: "default"
inputs:
  github-token:
    description: Github Token
    required: true
  title:
    description: "Milestone title"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const title = '${{ inputs.title }}';
          const milestones = await github.rest.issues.listMilestones({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const milestone = milestones.data.find(m => m.title === title);
          if (!milestone) {
            console.error(`Milestone '${title}' not found.`);
            return;
          }
          await github.rest.issues.updateMilestone({
            owner: context.repo.owner,
            repo: context.repo.repo,
            milestone_number: milestone.number,
            state: 'closed'
          });
          console.log(`Milestone '${title}' closed successfully!`);
