name: "default"
description: "default"
inputs:
  github-token:
    description: Github Token
    required: true
  title:
    description: "Milestone title"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const title = '0.0.1';
          const milestones = await github.rest.issues.listMilestones({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const milestone = milestones.data.find(m => m.title === title);
          if (!milestone) {
            console.error(`Milestone '${milestoneTitle}' not found.`);
            return;
          }
          await github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            milestone: milestone.number
          });
