name: "deploy"
description: "deploy"
inputs:
  rubygems-token:
    description: "RubyGems token"
  hook-version-file:
    description: "Hook version file (for pre-release version)"
  hook-version-suffix:
    description: "Version suffix (for re-release version)"

runs:
  using: "composite"
  steps:
    - if: inputs.hook-version-file && inputs.hook-version-suffix
      run: |
        echo -n $(head -n 1 ${{ inputs.hook-version-file }})${{ inputs.hook-version-suffix }} > ${{ inputs.hook-version-file }}
        echo "version = $(cat ${{ inputs.hook-version-file }})"
      shell: bash
    - if: inputs.rubygems-token
      run: |
        mkdir -p ~/.gem
        echo "---" >> ~/.gem/credentials
        echo ":rubygems_api_key: ${{ inputs.rubygems-token }}" >> ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem build
        find *.gem -exec gem push {} \;
        rm -rf *.gem ~/.gem/credentials
      shell: bash
