name: "default"
description: "default"
inputs:
  checkout:
    description: "Whether to check out the project"
    default: true
  submodules:
    description: "Whether to check out submodules"
    default: false
  ruby-version:
    description: "Ruby version"
    required: true
    default: '3.0'
  bundle-install:
    description: "Running bundle install"
    default: false
  bundle-config-path:
    description: "Location to install gems"
    default: ~/.bundle

runs:
  using: "composite"
  steps:
    - if: inputs.checkout
      uses: actions/checkout@v3
      with:
        submodules: ${{ inputs.submodules }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
    - if: inputs.bundle-install && inputs.bundle-config-path
      run: bundle config path ${{ inputs.bundle-config-path }}
      shell: bash
    - if: inputs.bundle-install
      run: bundle install
      shell: bash
