name: "default"
description: "default"
inputs:
  bundle-install:
    description: "Running bundle install"
  pod-install:
    description: "Running bundle install"
  working-dir:
    description: "Working dir"
    default: "."
  ruby-version:
    description: "Ruby version"
  python-version:
    description: "Python version"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      if: inputs.ruby-version
      with:
        ruby-version: ${{ inputs.ruby-version }}
    - uses: actions/setup-python@v4
      if: inputs.python-version
      with:
        python-version: ${{ inputs.python-version }}
    - if: inputs.bundle-install
      working-directory: ${{ inputs.working-dir }}
      run: bundle install
      shell: bash
    - if: inputs.pod-install
      working-directory: ${{ inputs.working-dir }}
      run: bundle exec pod install || (echo "Retry with --repo-update" && bundle exec pod install --repo-update)
      shell: bash
