name: Deploy
on:
  workflow_call:
    inputs:
      deploy-rc:
        description: Deploy a RC version
        type: boolean
      deploy-stable:
        description: Deploy a stable version
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
      RUBYGEMS_TOKEN:
        required: true

jobs:
  deploy-rc:
    if: ${{ inputs.deploy-rc }}
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/rb/install@main
        with:
          bundle-install: true
      - name: Deploy
        uses: trinhngocthuyen/gh-actions/rb/deploy@main
        with:
          rubygems-token: ${{ secrets.RUBYGEMS_TOKEN }}
          hook-version-file: VERSION
          hook-version-suffix: .rc${{ github.run_id }}

  deploy-stable:
    if: ${{ inputs.deploy-stable }}
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/rb/install@main
        with:
          bundle-install: true
      - name: Deploy
        uses: trinhngocthuyen/gh-actions/rb/deploy@main
        with:
          rubygems-token: ${{ secrets.RUBYGEMS_TOKEN }}
          hook-version-file: VERSION
      - name: Create a release
        uses: trinhngocthuyen/gh-actions/gh/release@main
        with:
          version-file: VERSION
          generate-release-notes: true
          token: ${{ secrets.GH_TOKEN }}
      - name: Bump version
        uses: trinhngocthuyen/gh-actions/core/bump_version@main
        with:
          version-file: VERSION
      - name: Bundle
        run: bundle # To update this gem's version in Gemfile.lock
        shell: bash
      - name: Push changes
        uses: trinhngocthuyen/gh-actions/git/push@main
        with:
          commit_msg: "CHORE: Bump version"
          token: ${{ secrets.GH_TOKEN }}
